export const COUNTRY_FLAGS: Record<string, string> = {
  // 한글
  '일본': '🇯🇵',
  '프랑스': '🇫🇷',
  '태국': '🇹🇭',
  '인도네시아': '🇮🇩',
  '싱가포르': '🇸🇬',
  '영국': '🇬🇧',
  '스페인': '🇪🇸',
  '호주': '🇦🇺',
  '미국': '🇺🇸',
  '베트남': '🇻🇳',
  '필리핀': '🇵🇭',
  '대만': '🇹🇼',
  '이탈리아': '🇮🇹',
  '독일': '🇩🇪',
  '네덜란드': '🇳🇱',
  '포르투갈': '🇵🇹',
  '그리스': '🇬🇷',
  '터키': '🇹🇷',
  'UAE': '🇦🇪',
  '인도': '🇮🇳',
  '중국': '🇨🇳',
  '홍콩': '🇭🇰',
  '말레이시아': '🇲🇾',
  '캐나다': '🇨🇦',
  '멕시코': '🇲🇽',
  '스위스': '🇨🇭',
  '오스트리아': '🇦🇹',
  '체코': '🇨🇿',
  '헝가리': '🇭🇺',
  '폴란드': '🇵🇱',
  '스웨덴': '🇸🇪',
  '덴마크': '🇩🇰',
  '핀란드': '🇫🇮',
  '노르웨이': '🇳🇴',
  '벨기에': '🇧🇪',
  '괌': '🇬🇺',
  '사이판': '🇲🇵',
  // 영어 (풀네임)
  'Japan': '🇯🇵',
  'France': '🇫🇷',
  'Thailand': '🇹🇭',
  'Indonesia': '🇮🇩',
  'Singapore': '🇸🇬',
  'UK': '🇬🇧',
  'United Kingdom': '🇬🇧',
  'Spain': '🇪🇸',
  'Australia': '🇦🇺',
  'USA': '🇺🇸',
  'United States': '🇺🇸',
  'Vietnam': '🇻🇳',
  'Philippines': '🇵🇭',
  'Taiwan': '🇹🇼',
  'Italy': '🇮🇹',
  'Germany': '🇩🇪',
  'Netherlands': '🇳🇱',
  'Portugal': '🇵🇹',
  'Greece': '🇬🇷',
  'Turkey': '🇹🇷',
  'India': '🇮🇳',
  'China': '🇨🇳',
  'Hong Kong': '🇭🇰',
  'Malaysia': '🇲🇾',
  'Canada': '🇨🇦',
  'Mexico': '🇲🇽',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Czech Republic': '🇨🇿',
  'Hungary': '🇭🇺',
  'Poland': '🇵🇱',
  'Sweden': '🇸🇪',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Norway': '🇳🇴',
  'Belgium': '🇧🇪',
  'Guam': '🇬🇺',
  'Saipan': '🇲🇵',
  // 영어 슬러그 (소문자, en/destinations용)
  'japan': '🇯🇵',
  'france': '🇫🇷',
  'thailand': '🇹🇭',
  'indonesia': '🇮🇩',
  'singapore': '🇸🇬',
  'uk': '🇬🇧',
  'spain': '🇪🇸',
  'australia': '🇦🇺',
  'usa': '🇺🇸',
  'vietnam': '🇻🇳',
  'philippines': '🇵🇭',
  'taiwan': '🇹🇼',
  'italy': '🇮🇹',
  'germany': '🇩🇪',
  'netherlands': '🇳🇱',
  'portugal': '🇵🇹',
  'greece': '🇬🇷',
  'turkey': '🇹🇷',
  'india': '🇮🇳',
  'china': '🇨🇳',
  'hong-kong': '🇭🇰',
  'malaysia': '🇲🇾',
  'canada': '🇨🇦',
  'mexico': '🇲🇽',
  'switzerland': '🇨🇭',
  'austria': '🇦🇹',
  'czech': '🇨🇿',
  'hungary': '🇭🇺',
  'poland': '🇵🇱',
  'sweden': '🇸🇪',
  'denmark': '🇩🇰',
  'finland': '🇫🇮',
  'norway': '🇳🇴',
  'belgium': '🇧🇪',
  'guam': '🇬🇺',
  'cnmi': '🇲🇵',
}

export function getCountryFlag(country: string): string {
  return COUNTRY_FLAGS[country] ?? '🌍'
}
