// 섹션 타이틀 → Unsplash 검색 키워드 변환
// 장소명 직접 매핑(최우선) → 카테고리 키워드 → 영문 제목 → 기본값 순으로 처리
export function getSectionImageKeyword(sectionTitle: string, cityEn: string): string {
  const title = sectionTitle.toLowerCase()
  const city = cityEn.toLowerCase()

  // ── 1. 특정 장소명 직접 매핑 (최우선) ────────────────────────────────
  const placeKeywords: Record<string, string> = {
    // 도쿄
    '센소지': 'senso-ji temple asakusa tokyo lantern',
    '시부야': 'shibuya crossing tokyo pedestrian crowd',
    '신주쿠': 'shinjuku tokyo neon night entertainment',
    '하라주쿠': 'harajuku takeshita street fashion tokyo',
    '긴자': 'ginza tokyo luxury shopping district',
    '아키하바라': 'akihabara tokyo electronics anime street',
    '우에노': 'ueno park tokyo cherry blossom pond',
    '롯폰기': 'roppongi tokyo nightlife art tower',
    '오다이바': 'odaiba tokyo bay rainbow bridge waterfront',
    '아사쿠사': 'asakusa tokyo traditional temple lantern',
    '츠키지': 'tsukiji fish market tokyo seafood',
    '이케부쿠로': 'ikebukuro tokyo shopping crowd station',
    '시모키타자와': 'shimokitazawa tokyo vintage bohemian',
    '야나카': 'yanaka tokyo old town traditional',
    '오모테산도': 'omotesando tokyo fashion boulevard zelkova',
    // 오사카
    '도톤보리': 'dotonbori osaka canal neon glico sign',
    '오사카성': 'osaka castle historic stone wall landmark',
    '신세카이': 'shinsekai osaka retro tsutenkaku tower',
    '우메다': 'umeda osaka modern shopping skybuilding',
    '난바': 'namba osaka shopping entertainment district',
    '구로몬': 'kuromon ichiba osaka market fresh food',
    '아메리카무라': 'america village osaka street fashion youth',
    // 교토
    '후시미이나리': 'fushimi inari shrine torii gates kyoto path',
    '기온': 'gion geisha district kyoto traditional lantern',
    '아라시야마': 'arashiyama bamboo grove kyoto path green',
    '킨카쿠지': 'kinkaku-ji golden pavilion kyoto reflection pond',
    '철학의길': 'philosopher path kyoto canal cherry blossom',
    '니시키시장': 'nishiki market kyoto fresh food traditional',
    '청수사': 'kiyomizu-dera temple kyoto wooden stage',
    '기요미즈데라': 'kiyomizu-dera temple kyoto wooden stage',
    '교토타워': 'kyoto tower skyline city view',
    '금각사': 'kinkaku-ji golden pavilion kyoto reflection',
    // 후쿠오카
    '나카스': 'nakasu fukuoka yatai food stalls river night',
    '캐널시티': 'canal city fukuoka shopping mall waterfall',
    '다자이후': 'dazaifu tenmangu shrine plum fukuoka',
    '모모치': 'momochi fukuoka beach tower seaside',
    '하카타': 'hakata fukuoka station ramen traditional',
    '텐진': 'tenjin fukuoka shopping underground mall',
    // 삿포로
    '오도리공원': 'odori park sapporo snow festival winter',
    '스스키노': 'susukino sapporo night entertainment neon',
    '삿포로맥주': 'sapporo beer garden historic red brick',
    // 나고야
    '나고야성': 'nagoya castle golden dolphins landmark',
    '오스': 'osu nagoya shopping arcade vintage',
    // 도쿄 근교
    '하코네': 'hakone mount fuji lake onsen ryokan',
    '닛코': 'nikko toshogu shrine gold ornate',
    '가마쿠라': 'kamakura great buddha giant bronze statue',
    '요코하마': 'yokohama chinatown harbor landmark ferris',
    // 베트남
    '호이안': 'hoi an ancient town lantern river vietnam',
    '다낭해변': 'da nang beach my khe vietnam blue sea',
    '바나힐': 'ba na hills golden bridge giant hands vietnam',
    '하롱베이': 'ha long bay limestone karst vietnam emerald',
    '미선': 'my son sanctuary vietnam hindu ruins ancient',
    '호치민': 'ho chi minh city reunification palace vietnam',
    '벤탄': 'ben thanh market ho chi minh vietnam street',
    // 태국
    '왓포': 'wat pho reclining buddha bangkok golden temple',
    '왓아룬': 'wat arun temple bangkok river dawn sunset',
    '카오산로드': 'khao san road bangkok backpacker street night',
    '짜뚜짝': 'chatuchak weekend market bangkok shopping',
    '왕궁': `grand palace ${city} royal golden intricate`,
    '왓프라깨우': 'grand palace emerald buddha bangkok temple',
    '아시아티크': 'asiatique bangkok waterfront night market river',
    '치앙마이올드시티': 'chiang mai old city moat temple brick',
    '도이수텝': 'doi suthep temple chiang mai mountain golden',
    '님만해민': 'nimmanhaemin road chiang mai hipster cafe',
    // 발리
    '우붓': 'ubud bali rice terrace jungle temple',
    '따나롯': 'tanah lot temple bali sunset ocean rocks',
    '꾸따': 'kuta beach bali sunset surfer golden sand',
    '스미냑': 'seminyak bali luxury beach club sunset',
    '울루와뚜': 'uluwatu temple bali cliff sunset ocean',
    '짱구': 'canggu bali surf beach cafe rice paddy',
    '누사두아': 'nusa dua bali luxury resort white beach',
    '사누르': 'sanur bali calm beach sunrise traditional',
    '클룽쿵': 'klungkung bali traditional palace ancient',
    '킨타마니': 'kintamani bali volcano lake mountain view',
    // 싱가포르
    '마리나베이': 'marina bay sands singapore skyline infinity pool',
    '가든스바이더베이': 'gardens by the bay singapore supertree grove night',
    '차이나타운': 'chinatown singapore temple colorful shophouse',
    '리틀인디아': 'little india singapore colorful mustafa vibrant',
    '센토사': 'sentosa island singapore beach resort universal',
    '클락키': 'clarke quay singapore river bar night lights',
    '오차드로드': 'orchard road singapore shopping mall luxury',
    '부기스': 'bugis singapore heritage street market',
    '라오파삿': 'lau pa sat singapore satay food hawker',
    // 서울
    '경복궁': 'gyeongbokgung palace seoul traditional mountain',
    '창덕궁': 'changdeokgung palace secret garden seoul',
    '명동': 'myeongdong seoul shopping street food cosmetic',
    '홍대': 'hongdae seoul street art youth live music',
    '이태원': 'itaewon seoul multicultural district',
    '북촌': 'bukchon hanok village seoul traditional roof',
    '남산': 'namsan tower seoul city view hill',
    '강남': 'gangnam seoul modern skyscraper district',
    '인사동': 'insadong seoul traditional arts craft teashop',
    '동대문': 'dongdaemun market seoul fashion shopping night',
    '잠실': 'jamsil seoul lotte world amusement',
    '한강': 'han river seoul park picnic bridge',
    '을지로': 'euljiro seoul retro old town neon print',
    '성수동': 'seongsu dong seoul hipster factory cafe',
    // 제주
    '한라산': 'hallasan mountain jeju volcanic crater crater',
    '성산일출봉': 'seongsan ilchulbong jeju crater sunrise',
    '협재해변': 'hyeopjae beach jeju turquoise sand',
    // 홍콩
    '빅토리아피크': 'victoria peak hong kong skyline harbor view',
    '몽콕': 'mong kok hong kong street market night neon',
    '란콰이퐁': 'lan kwai fong hong kong bar nightlife',
    '침사추이': 'tsim sha tsui hong kong harbor promenade',
    '스탠리': 'stanley market hong kong waterfront traditional',
    // 두바이
    '버즈칼리파': 'burj khalifa dubai skyscraper night fountain',
    '두바이몰': 'dubai mall shopping fountain underwater',
    '팜주메이라': 'palm jumeirah dubai aerial island luxury',
    '올드두바이': 'old dubai creek gold souk traditional',
    '사막': 'dubai desert safari dunes camel sunset',
    // 파리
    '에펠탑': 'eiffel tower paris night lights iconic',
    '루브르': 'louvre museum paris pyramid glass art',
    '몽마르트': 'montmartre paris sacre coeur bohemian',
    '샹젤리제': 'champs elysees paris boulevard arc de triomphe',
    '센강': 'seine river paris bridge boat cruise',
    // 런던
    '타워브릿지': 'tower bridge london thames river iconic',
    '빅벤': 'big ben london parliament westminster',
    '버킹엄궁': 'buckingham palace london royal guard',
    '코번트가든': 'covent garden london market performance',
    // 바르셀로나
    '사그라다파밀리아': 'sagrada familia barcelona gaudi cathedral',
    '람블라스': 'las ramblas barcelona pedestrian street',
    '구엘공원': 'park guell barcelona gaudi mosaic hill',
    // 이스탄불
    '하기아소피아': 'hagia sophia istanbul dome byzantine',
    '그랜드바자르': 'grand bazaar istanbul market carpet colorful',
    '보스포러스': 'bosphorus strait istanbul bridge europe asia',
    '블루모스크': 'blue mosque istanbul minaret sultan ahmet',
  }

  for (const [korean, english] of Object.entries(placeKeywords)) {
    if (title.includes(korean.toLowerCase())) return english
  }

  // ── 2. 카테고리 키워드 매핑 ───────────────────────────────────────────
  const categoryKeywords: Record<string, string> = {
    // 음식 세분화
    '맛집': `${city} best restaurant local food dining`,
    '길거리 음식': `${city} street food vendor market`,
    '길거리음식': `${city} street food vendor market`,
    '야시장': `${city} night market street food asia`,
    '라멘': 'ramen noodle soup broth japanese bowl',
    '스시': 'sushi japan fresh seafood platter',
    '야키토리': 'yakitori grilled chicken japanese skewer',
    '타코야키': 'takoyaki osaka octopus ball street food',
    '딤섬': 'dim sum chinese steamer basket traditional',
    '쌀국수': 'pho vietnamese noodle soup broth herbs',
    '팟타이': 'pad thai noodle street food thailand wok',
    '나시고렝': 'nasi goreng fried rice indonesia street',
    '카오만가이': 'khao man gai chicken rice thai simple',
    '분짜': 'bun cha grilled pork noodle vietnam charcoal',
    '바인미': 'banh mi vietnam baguette sandwich street',
    '음식': `${city} local cuisine traditional food dish`,
    '요리': `${city} cooking cuisine local authentic`,
    '카페': `${city} cafe coffee cozy interior brunch`,
    '커피': `${city} coffee shop specialty brew`,
    '디저트': `${city} dessert sweets pastry cafe`,
    '레스토랑': `${city} restaurant fine dining interior`,
    // 쇼핑
    '쇼핑': `${city} shopping street boutique fashion`,
    '백화점': `${city} department store luxury escalator`,
    '편의점': 'japan convenience store 7eleven lawson interior',
    '드럭스토어': 'matsumoto kiyoshi japanese drugstore cosmetics',
    '시장': `${city} local market fresh produce bazaar`,
    '아울렛': `${city} outlet mall shopping discount`,
    // 교통
    '신칸센': 'shinkansen bullet train japan speed rail',
    '지하철': `${city} subway metro train station platform`,
    '버스': `${city} bus public transport street`,
    '택시': `${city} taxi cab city street`,
    '공항': `${city} airport terminal runway aviation`,
    '교통': `${city} transportation metro street map`,
    '이동': `${city} transport public city map`,
    // 숙소
    '료칸': 'ryokan japanese inn tatami onsen garden',
    '호스텔': 'hostel dorm backpacker budget travel social',
    '캡슐호텔': 'capsule hotel japan pod sleeping compact',
    '게스트하우스': 'guesthouse cozy room travel budget',
    '리조트': `${city} resort pool infinity luxury sea`,
    '호텔': `${city} hotel lobby luxury accommodation room`,
    '에어비앤비': 'airbnb apartment cozy home travel living',
    // 관광
    '박물관': `${city} museum exhibition gallery interior`,
    '미술관': `${city} art gallery modern exhibition light`,
    '공원': `${city} park garden green nature bench`,
    '성': `${city} castle fortress stone historic wall`,
    '신사': 'shinto shrine torii gate japan red forest',
    '절': `${city} buddhist temple incense stone lantern`,
    '사원': `${city} temple ancient pagoda sacred`,
    '성당': `${city} cathedral church gothic architecture`,
    '해변': `${city} beach ocean waves tropical palm`,
    '섬': `${city} island tropical beach paradise`,
    '온천': `${city} onsen hot spring traditional ryokan`,
    '산': `${city} mountain hiking trail summit view`,
    '폭포': `${city} waterfall nature jungle tropical`,
    '호수': `${city} lake reflection mountain nature`,
    '야경': `${city} night city skyline lights reflection`,
    '일몰': `${city} sunset golden hour sky ocean horizon`,
    '일출': `${city} sunrise dawn mountain sea sky`,
    '관광': `${city} tourist landmark sightseeing famous`,
    '명소': `${city} famous place landmark scenic popular`,
    '랜드마크': `${city} landmark iconic building city`,
    // 액티비티
    '다이빙': 'scuba diving underwater coral reef tropical fish',
    '서핑': 'surfing wave beach ocean boarder sport',
    '스노클링': 'snorkeling coral reef clear water tropical fish',
    '트레킹': 'trekking hiking mountain trail adventure',
    '하이킹': 'hiking trail mountain nature adventure outdoor',
    '래프팅': 'rafting river adventure water sport',
    '골프': 'golf course fairway green resort',
    '스파': 'spa massage relaxation wellness candle',
    '액티비티': `${city} outdoor adventure activity sport`,
    '체험': `${city} experience cultural workshop hands-on`,
    // 계절/날씨
    '벚꽃': 'cherry blossom sakura spring pink japan',
    '단풍': 'autumn fall foliage red maple leaves path',
    '눈축제': 'snow festival winter lights ice sculpture',
    '눈': 'snow winter cold landscape frost',
    '여름': 'summer travel sunshine beach warm',
    '우기': 'tropical rain monsoon green lush asia',
    '장마': 'rain umbrella monsoon wet season',
    // 문화
    '기모노': 'kimono traditional japanese dress woman street',
    '한복': 'hanbok traditional korean dress colorful palace',
    '마쓰리': 'matsuri japanese festival parade mikoshi',
    '축제': `${city} festival celebration traditional street`,
    '공연': `${city} performance show stage entertainment`,
    '문화': `${city} culture tradition local life authentic`,
    '역사': `${city} historical heritage ancient architecture`,
    '전통': `${city} traditional craft culture village`,
    // 실용 정보
    '비자': 'passport visa immigration airport travel document',
    '입국': 'airport arrival immigration gate terminal',
    '환전': 'currency exchange money forex travel bills',
    '유심': 'sim card smartphone travel connectivity',
    '와이파이': 'wifi hotspot digital nomad laptop travel',
    '안전': 'travel safety precaution guide map street',
    '준비': 'travel packing luggage checklist preparation',
    '예산': 'budget travel saving money backpacker',
    '꿀팁': 'travel tips insider local secret guide',
    '팁': `${city} travel tips practical guide`,
    '소개': `${city} city overview aerial panorama skyline`,
    '개요': `${city} city panorama overview aerial view`,
    '기본정보': `${city} travel essential information guide`,
    '기본 정보': `${city} travel essential information guide`,
    '일정': `${city} travel map itinerary route scenic`,
    '코스': `${city} route walking path sightseeing`,
  }

  for (const [korean, english] of Object.entries(categoryKeywords)) {
    if (title.includes(korean.toLowerCase())) return english
  }

  // ── 3. 영문 섹션 타이틀 매핑 ─────────────────────────────────────────
  const englishKeywords: Record<string, string> = {
    'top attractions': `${city} famous tourist landmark sightseeing`,
    'best restaurants': `${city} best restaurant dining local food`,
    'where to eat': `${city} restaurant dining food local`,
    'street food': `${city} street food market vendor`,
    'must eat': `${city} local food cuisine dish`,
    'food guide': `${city} cuisine food dish traditional`,
    'shopping': `${city} shopping district boutique fashion`,
    'where to shop': `${city} shopping street market retail`,
    'transportation': `${city} public transport metro station map`,
    'getting around': `${city} transport navigation city map`,
    'getting there': `${city} airport arrival transportation`,
    'how to get': `${city} transport airport train station`,
    'accommodation': `${city} hotel resort stay luxury`,
    'where to stay': `${city} hotel accommodation neighborhood`,
    'best hotels': `${city} hotel luxury interior modern`,
    'nightlife': `${city} night entertainment bar light`,
    'night market': `${city} night market street food lantern`,
    'day trips': `${city} nearby scenic excursion landscape`,
    'nearby': `${city} surroundings nearby town scenic`,
    'nature': `${city} nature landscape outdoor mountain`,
    'beaches': `${city} beach ocean tropical sand waves`,
    'temples': `${city} temple shrine ancient sacred`,
    'castles': `${city} castle fortress historic stone`,
    'museums': `${city} museum exhibition gallery art`,
    'parks': `${city} park garden green nature`,
    'travel tips': `${city} travel tips practical essential`,
    'practical info': `${city} travel information essential`,
    'visa': 'passport visa travel document airport immigration',
    'weather': `${city} weather landscape sky season`,
    'budget': `${city} budget travel saving money tips`,
    'safety': 'travel safety guide tips city street',
    'culture': `${city} culture tradition local life`,
    'history': `${city} historical ancient architecture heritage`,
    'festivals': `${city} festival celebration event traditional`,
    'coffee shops': `${city} cafe coffee specialty cozy interior`,
    'hidden gems': `${city} hidden spot local secret authentic`,
    'instagram': `${city} scenic photo spot beautiful view`,
    'photo spots': `${city} photography scenic beautiful landmark`,
    'local life': `${city} local neighborhood market daily life`,
    'introduction': `${city} city skyline aerial panorama overview`,
    'overview': `${city} city panorama overview skyline aerial`,
    'activities': `${city} outdoor adventure activities sport`,
    'things to do': `${city} activities tourist popular things`,
    'itinerary': `${city} travel route map scenic itinerary`,
    'kpop': 'kpop seoul music idol concert fandom',
    'k-drama': 'kdrama filming location seoul palace traditional',
    'onsen': 'onsen hot spring japan ryokan steam nature',
    'ryokan': 'ryokan japanese inn tatami garden traditional',
    'sushi': 'sushi japan fresh seafood restaurant counter',
    'ramen': 'ramen noodle soup broth japanese bowl',
    'hiking': `${city} hiking trail mountain nature outdoor`,
    'trekking': `${city} trekking mountain trail forest`,
    'diving': 'scuba diving underwater coral tropical fish',
    'surfing': 'surfing wave ocean beach sport board',
    'spa': 'spa massage relaxation wellness treatment',
    'cruise': `${city} harbor cruise boat water skyline`,
    'sunset': `${city} sunset golden hour sky horizon`,
    'sunrise': `${city} sunrise dawn mountain sea sky`,
  }

  for (const [english, keyword] of Object.entries(englishKeywords)) {
    if (title.includes(english.toLowerCase())) return keyword
  }

  // ── 4. 기본값 ────────────────────────────────────────────────────────
  // 영문이 포함된 제목: 영문 부분 추출
  const englishPart = sectionTitle.match(/[A-Za-z][A-Za-z\s\-']{3,}/g)?.find(w => w.trim().length > 3)
  if (englishPart) return `${city} ${englishPart.trim().toLowerCase()}`

  // 한글만 있는 경우: 도시 기본 이미지
  const hasKorean = /[가-힣]/.test(sectionTitle)
  if (hasKorean) return `${city} travel landmark scenic`

  return `${city} ${sectionTitle.toLowerCase()}`
}
